#################################
# PID parameters for pose seeking
#################################

# Maximum value of error integral for all PID controllers
windup_limit: 0.1 # 0.05

# PID gains
x_proportional_gain: 7.5
y_proportional_gain: 7.5
z_proportional_gain: 7.5
x_integral_gain: 0.5
y_integral_gain: 0.5
z_integral_gain: 0.5
x_derivative_gain: 1.7
y_derivative_gain: 1.7
z_derivative_gain: 1.7

angular_proportional_gain: 7.0
angular_integral_gain: 0.5
angular_derivative_gain: 1.5

# x_proportional_gain: 6.7
# y_proportional_gain: 6.7
# z_proportional_gain: 7.5
# x_integral_gain: 0.5
# y_integral_gain: 0.5
# z_integral_gain: 0.5
# x_derivative_gain: 1.7
# y_derivative_gain: 1.7
# z_derivative_gain: 1.7

# angular_proportional_gain: 5.2
# angular_integral_gain: 0.5
# angular_derivative_gain: 0.7