#################################
# PID parameters for pose seeking
#################################

# Maximum value of error integral for all PID controllers
windup_limit: 0.02 # 0.05

# PID gains
x_proportional_gain: 4.5
y_proportional_gain: 4.5
z_proportional_gain: 4.5
x_integral_gain: 0.35
y_integral_gain: 0.35
z_integral_gain: 0.35
x_derivative_gain: 0.2
y_derivative_gain: 0.2
z_derivative_gain: 0.2

angular_proportional_gain: 3.5
angular_integral_gain: 0.3
angular_derivative_gain: 0.2