# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # left_arm_effort_controller:
    #   type: effort_controllers/JointGroupEffortController

    # right_arm_effort_controller:
    #   type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_hand_controller:
      type: forward_command_controller/ForwardCommandController

    right_gripper_controller:
      type: forward_command_controller/ForwardCommandController

    left_cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

    right_cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

left_cartesian_motion_controller:
  ros__parameters:
    end_effector_link: "tcp_l"
    robot_base_link: "base_link"
    joints:
      - arm_J1_l
      - arm_J2_l
      - arm_J3_l
      - arm_J4_l
      - arm_J5_l
      - arm_J6_l
      - arm_J7_l
    command_interfaces:
      - position
    solver:
        error_scale: 1.0
        iterations: 20
    pd_gains:
      trans_x: {p: 6.5, d: 0.7}
      trans_y: {p: 6.5, d: 0.7}
      trans_z: {p: 6.5, d: 0.7}
      rot_x: {p: 5.7, d: 0.5}
      rot_y: {p: 5.7, d: 0.5}
      rot_z: {p: 5.7, d: 0.5}

right_cartesian_motion_controller:
  ros__parameters:
    end_effector_link: "tcp_r"
    robot_base_link: "base_link"
    joints:
      - arm_J1_r
      - arm_J2_r
      - arm_J3_r
      - arm_J4_r
      - arm_J5_r
      - arm_J6_r
      - arm_J7_r
    command_interfaces:
      - position
    solver:
      error_scale: 1.0
      iterations: 20
    pd_gains:
      trans_x: {p: 6.5, d: 0.7}
      trans_y: {p: 6.5, d: 0.7}
      trans_z: {p: 6.5, d: 0.7}
      rot_x: {p: 5.7, d: 0.5}
      rot_y: {p: 5.7, d: 0.5}
      rot_z: {p: 5.7, d: 0.5}

left_arm_controller:
  ros__parameters:
    joints:
      - arm_J1_l
      - arm_J2_l
      - arm_J3_l
      - arm_J4_l
      - arm_J5_l
      - arm_J6_l
      - arm_J7_l
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    open_loop_control: false
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 60.0
      arm_J1_l:
        trajectory: 1.0
        goal: 0.2
      arm_J2_l:
        trajectory: 1.0
        goal: 0.2
      arm_J3_l:
        trajectory: 1.0
        goal: 0.2
      arm_J4_l:
        trajectory: 1.0
        goal: 0.2
      arm_J5_l:
        trajectory: 1.0
        goal: 0.2
      arm_J6_l:
        trajectory: 1.0
        goal: 0.2
      arm_J7_l:
        trajectory: 1.0
        goal: 0.2


right_arm_controller:
  ros__parameters:
    joints:
      - arm_J1_r
      - arm_J2_r
      - arm_J3_r
      - arm_J4_r
      - arm_J5_r
      - arm_J6_r
      - arm_J7_r
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    open_loop_control: false
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 60.0
      arm_J1_r:
        trajectory: 1.0
        goal: 0.2
      arm_J2_r:
        trajectory: 1.0
        goal: 0.2
      arm_J3_r:
        trajectory: 1.0
        goal: 0.2
      arm_J4_r:
        trajectory: 1.0
        goal: 0.2
      arm_J5_r:
        trajectory: 1.0
        goal: 0.2
      arm_J6_r:
        trajectory: 1.0
        goal: 0.2
      arm_J7_r:
        trajectory: 1.0
        goal: 0.2

# left_arm_effort_controller:
#   ros__parameters:
#     joints:
#       - joint1_left
#       - joint2_left
#       - joint3_left
#       - joint4_left
#       - joint5_left
#       - joint6_left
#       - joint7_left

# right_arm_effort_controller:
#   ros__parameters:
#     joints:
#       - joint1_right
#       - joint2_right
#       - joint3_right
#       - joint4_right
#       - joint5_right
#       - joint6_right
#       - joint7_right

left_hand_controller:
  ros__parameters:
    joints:
      - hand_J1_l
      - hand_J2_l
      - hand_J2_l_1
      - hand_J2_l_2
      - hand_J3_l
      - hand_J3_l_1
      - hand_J4_l
      - hand_J4_l_1
      - hand_J5_l
      - hand_J5_l_1
      - hand_J6_l
      - hand_J6_l_1
    interface_name: position

right_gripper_controller:
  ros__parameters:
    joints:
      - gripper_J1_r
    interface_name: position