<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dual_arm_hardware_interface</name>
  <version>0.1.0</version>
  <description>dual_arm hardware interface for ROS2</description>
  <maintainer email="mskwok@email.com">mskwok</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>boost</depend>
  <depend>dual_arm_v2_2_control_sdk</depend>

  <build_depend>rclcpp</build_depend>
  <build_depend>rclcpp_lifecycle</build_depend>
  <build_depend>hardware_interface</build_depend>
  <build_depend>pluginlib</build_depend>
  <build_depend>lifecycle_msgs</build_depend>
  <build_depend>diagnostic_updater</build_depend>

  <exec_depend>rclcpp</exec_depend>
  <exec_depend>rclcpp_lifecycle</exec_depend>
  <exec_depend>hardware_interface</exec_depend>
  <exec_depend>pluginlib</exec_depend>
  <exec_depend>lifecycle_msgs</exec_depend>
  <exec_depend>diagnostic_updater</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <build_export_depend>hardware_interface</build_export_depend>
    <build_export_depend>controller_interface</build_export_depend>
    <hardware_interface plugin="${prefix}/dual_arm_hardware_interface_plugin.xml"/>
  </export>
  
</package>